version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./.docker/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./www:/var/www/html
    depends_on:
      - php
  php:
    user: "www" # insert either uid or name of the user
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"  
    volumes:
      - ./www:/var/www/html

      
  db:
    image: mariadb:10.7
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mariadb:/var/lib/mysql 
    environment:
      - MYSQL_ROOT_PASSWORD=pw
      - MYSQL_PASSWORD=pw
  